timeout: 5
triggers:
  - name: merge-request
    type: github_pr
    runs:
      - name: flake8
        container: python:3.5-alpine
        host-tag: amd64
        script: flake8

scripts:
  flake8: |
    #!/bin/sh -ex
    pip3 install flake8
    flake8 --ignore=E722 --exclude=migrations/ ./
